### ISSUE TITLE
No ctest available

### ISSUE THREAD

**Issue by bernecky** [SacBase/LivermoreLoops#2]
There is no ctest script for the Livermore Loops.

`cmake; make -j`

do work correctly, though.

**Comment by hv15** [comment]
What do you mean by ctest script? I don't think this project needs unit tests...

**Comment by bernecky** [comment]
Well, I had so much fun with the apex unit tests that I got carried away, I guess.

The ctest stuff has some handy features, such as letting me easily test seq and mt_pth cases, the latter
with varying numbers of threads. The idea of having a uniform way to build and execute 
performance tests, as well as unit tests, just seems natural and simple to me.

At present, I don't see any documentation about performance testing for the Livermore Loops,
despite there being several variants for most of the tests, e.g., "loop08.vers".
Yes, I could dig through the code and figure it out, and perhaps write a Makefile
to automate execution of them, but why would anybody go to all the work of 
writing variant codes (that might or might not produce the same results), and
leave not one whit of documentation in the folders to let the great unwashed 
know what they were trying to do, and why.

**Comment by bernecky** [comment]
I have a merge request for cmake-common that introduces ctest support.
Perhaps you can check it and perhaps approve that?

**Comment by bernecky** [comment]
PR #4 (a few minutes ago) supports ctest now. Most of the tests run clean in seq and mt_pth mode, except for
loo08, which fails in what looks like at least two different modes. Heap corruption with -mt 2 and wrong answers.

The ctest stuff works well enough that I am going to close this issue, and create two new issues for the above faults.
